#!/usr/bin/env bash
# Script that pings an IP address passed as an argument.

# Accepts a string as an argument and IP 5 times..
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument

if [ "$#" -lt "1" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping "$1" -c 5
fi
